name: "TestApp.io Flutter App Distribution"
description: "GitHub Action that uploads Flutter App artifacts to TestApp.io App Distribution"
author: "salemaljebaly@gmail.com"

on:
  push:
    branches:
      - deploy

jobs:
  export_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "12.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK to TestApp.io
        uses: testappio/github-action@v5
        with:
          api_token: ${{secrets.TESTAPPIO_API_TOKEN}}
          app_id: ${{secrets.TESTAPPIO_APP_ID}}
          
          file: build/app/outputs/flutter-apk/app-release.apk
          release_notes: "Testing manual debug notes..."
          git_release_notes: true
          include_git_commit_id: false
          notify: true